### PR TITLE
Improve Report Validation

### LINKED ISSUE #79: missing values on marshmallow deserialize
Many fields in the schema are not required but have no ``missing``or ``default`` values. We should probably set these fields so we know the once place where default values come in. The database storage_interface also won't work as is since the fields are not set at times.

### LINKED ISSUE #193: Improve report validation
There is no validation for requirements such as fx.interval_length < obs.interval_length in the API. This validation is performed in the DataModel and results in a value error thrown in the worker while it attempts to compute the report. From a user perspective, this just results in a failed report with no information about why the failure occurred. 

This issue presents itself directly when running locally with `USE_FAKE_REDIS = TRUE` because the computation is run immediately instead of being handed off to a worker, resulting in a 500.

The dashboard should definitely prevent this in the first place, but it should probably be handled elsewhere as well.  I see there being two ways to handle this:

- Load all of the object pairs and and validate them before storing or enqueueing and return errors.
- Handle errors in workers and store them in the report. This would need to go into core. I'd imagine enabling report templating to handle a failed report and display any errors raised during computation.

@alorenzo175, @wholmgren Do you guys have any thoughts about this? I think this is relatively minor, as the dashboard can help avoid these issues, but it's probably something we should handle eventually.

### PR DESCRIPTION
**Pull request by lboeman**
Trying to tackle a few issues related to Report Validation:
closes #193 - Primary part of this PR.
closes #79 - The remaining point in this issue is to providing missing/defaults to remaining report fields.
#147 - While working with the schema, it's probably worthwhile to improve on the API documentation related to reports.

### CODE REVIEW

**Comment by lboeman** [comment]
I think this is ready for a review. Should the API reject object pairs with a `forecast_type` of `probabilistic_forecast` that have a reference forecast?

**Comment by wholmgren** [comment]
We're going to add a CRPS skill score soon so I don't think it's worth putting in the effort to reject probabilistic forecasts that have a reference forecast.

**Comment by lboeman** [comment]
> We're going to add a CRPS skill score soon so I don't think it's worth putting in the effort to reject probabilistic forecasts that have a reference forecast.

Are there any further restrictions on probabilistic forecast groups? In this PR, I've only checked matching variable, site or aggregate, interval_length, interval_label and axis.

**Review by alorenzo175 — APPROVED** [review]
I feel like there is some special case would still get by this validation, but I can't remember what it was. If it crops up again, we can make a more detailed issue for it.

**Review by wholmgren — APPROVED** [review]
no, this is good

**Pull request merged**
